version: "3.8"
services:
  mongodb:
    container_name: "mongodb"
    image: "mongo"
    volumes:
      - data:/data/db
    #environment:
      #MONGO_INITDB_ROOT_USERNAME:niteshc
      #MONGO_INITDB_ROOT_PASSWORD:secret
      # - MONGO_INITDB_ROOT_USERNAME=niteshc
    env_file:
      - ./env/mongo.env
  backend:
    container_name: "backend"
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: "frontend"
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true    


volumes:
  data:
  logs:


# docker compose up
# docker compose up --build ## forces to build the image
# docker compose build ## forces to build the image
# docker compose down 
# docker compose down -v